#!/bin/bash -x

# Strict error checking
set -o errexit -o errtrace -o pipefail -o nounset

echo "##################### EXECUTE: aptly_management #####################"

# shellcheck disable=SC2012
KMS_DEB_PKG="$(ls -v -1 kurento-media-server_*.deb | tail -n 1)"
[ -z "$KMS_DEB_PKG" ] && { echo "Cannot find KMS package"; exit 1; }

KMS_VERSION="$(
    dpkg --field "$KMS_DEB_PKG" Version \
        | grep --perl-regexp --only-matching '^(\d+\.\d+\.\d+)'
)"
[ -z "$KMS_VERSION" ] && { echo "Cannot parse KMS Version field"; exit 1; }

aptly repo create -distribution="${DISTRIBUTION}" -component=kms6 "kurento-${DISTRIBUTION}-${KMS_VERSION}"
aptly repo add "kurento-${DISTRIBUTION}-${KMS_VERSION}" ./*.*deb
aptly snapshot create "snap-kurento-${DISTRIBUTION}-${KMS_VERSION}" from repo "kurento-${DISTRIBUTION}-${KMS_VERSION}"
aptly -gpg-key="${GPGKEY}" publish snapshot "snap-kurento-${DISTRIBUTION}-${KMS_VERSION}" "s3:ubuntu:${KMS_VERSION}"
