#!/usr/bin/env bash

# Uninstall every packge related to KMS and its development.



# Shell setup
BASEPATH="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"  # Absolute canonical path
# shellcheck source=bash.conf.sh
source "$BASEPATH/../bash.conf.sh" || {
    # Bash options for strict error checking
    set -o errexit -o errtrace -o pipefail -o nounset
}



# Check permissions
[[ "$(id -u)" -eq 0 ]] || {
    echo "ERROR: Please run as root user (or with 'sudo')"
    exit 1
}



# Uninstall everything
service kurento-media-server stop 2>/dev/null || true
aptitude purge --assume-yes '?installed?version(kurento)'
