#!/usr/bin/env bash

# Install packages needed to build Kurento Media Server.
#
# This script installs all development tools and pre-requisites that are needed
# to build a fresh copy of the Kurento Media Server source code. It does not
# install packages belonging to KMS itself.
#
# Notes:
# - gstreamer1.5-x is needed for the "timeoverlay" GStreamer plugin,
#   used by some tests in kms-elements.



# Shell setup
# -----------

BASEPATH="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"  # Absolute canonical path
# shellcheck source=bash.conf.sh
source "$BASEPATH/../bash.conf.sh" || exit 1



# Check permissions
# -----------------

[[ "$(id -u)" -eq 0 ]] || {
    log "ERROR: Please run as root user (or with 'sudo')"
    exit 1
}



# Ask for confirmation
# --------------------

echo "==== Install Kurento build dependencies ===="
echo "This script should be run from 'kms-omni-build'"
echo ""
read -p "Are you sure? Type 'yes': " -r SURE
if [[ "$SURE" != "yes" && "$SURE" != "YES" ]]; then
    echo "Exit ..."
    exit 0
fi



# Install Build-Depends
# ---------------------

apt-get update \
  && apt-get install --no-install-recommends --yes \
     git devscripts equivs

DIRS=(
    kurento-module-creator
    kms-cmake-utils
    kms-jsonrpc
    kms-core
    kms-elements
    kms-filters
    kurento-media-server
)
for DIR in "${DIRS[@]}"; do
    log "Install Build-Depends for '${DIR}'"
    mk-build-deps --install --remove \
        --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' \
        "${DIR}/debian/control"
done

log "All packages installed successfully"
