#!/usr/bin/env bash

# Install packages needed to build Kurento Media Server.
#
# This script installs all development tools and pre-requisites that are needed
# to build a fresh copy of the Kurento Media Server source code. It does not
# install packages belonging to KMS itself.
#
# Notes:
# - gstreamer1.5-x is needed for the "timeoverlay" GStreamer plugin,
#   used by some tests in kms-elements.



# Shell setup
# -----------

BASEPATH="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"  # Absolute canonical path
# shellcheck source=bash.conf.sh
source "$BASEPATH/../bash.conf.sh" || {
    # Bash options for strict error checking
    set -o errexit -o errtrace -o pipefail -o nounset
    shopt -s inherit_errexit 2>/dev/null || true
}



# Check permissions
# -----------------

[[ "$(id -u)" -eq 0 ]] || {
    echo "ERROR: Please run as root user (or with 'sudo')"
    exit 1
}



# Install Build-Depends
# ---------------------

apt-get update && apt-get install --no-install-recommends --yes \
    ca-certificates git gnupg devscripts equivs

DIRS=(
    kurento-module-creator
    kms-cmake-utils
    kms-jsonrpc
    kms-core
    kms-elements
    kms-filters
    kurento-media-server
)
for DIR in "${DIRS[@]}"; do
    echo "+ Install Build-Depends for '${DIR}'"
    DEBIAN_FRONTEND=noninteractive \
    mk-build-deps --install --remove \
        --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' \
        "${DIR}/debian/control"
done

echo "All packages installed successfully"
