#!/usr/bin/env bash
set -eu -o pipefail  # Abort on errors, disallow undefined variables
IFS=$'\n\t'          # Apply word splitting only on newlines and tabs

# Install every package related to Kurento Media Server.
#
# This script calls the other ones in order to install every package.
#
# Changes:
# 2018-03-16 Juan Navarro <juan.navarro@gmx.es>
# - Initial version.
# 2018-03-23
# - Add log function.

# Set up logging function
BASENAME="$(basename "$0")"  # Complete file name
log() { echo "[$BASENAME] $*"; }

# Check root permissions
[ "$(id -u)" -eq 0 ] || { log "Please run as root"; exit 1; }

FILES=(
    kurento-install-debugging-2018
    kurento-install-development
    kurento-install-kms-2018
    kurento-install-packaging
)

# Parse command line arguments
update=1
while getopts 'n' flag; do
  case "${flag}" in
    n) update=0 ;;
    *) ;;
  esac
done

(( $update )) && apt-get update

# Set PATH so scripts can be called by name, without './'
BASEPATH="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"  # Absolute canonical path
PATH="$BASEPATH:${PATH:-}"

# Run a loop over all names and run them.
for FILE in "${FILES[@]}"; do
    log "Run: $FILE"
    "$FILE" -n
done

log "All install scripts ran successfully"

# ------------

log "Done."
