#!/usr/bin/env bash
set -eu -o pipefail  # Abort on errors, disallow undefined variables
IFS=$'\n\t'          # Apply word splitting only on newlines and tabs

# Configure the Kurento package repository for `apt-get`.
#
# Changes:
# 2017-10-03 Juan Navarro <juan.navarro@gmx.es>
# - Initial version.
# 2018-03-23
# - Add log function.

# Set up logging function
BASENAME="$(basename "$0")"  # Complete file name
log() { echo "[$BASENAME] $*"; }

# Check root permissions
[ "$(id -u)" -eq 0 ] || { log "Please run as root"; exit 1; }

# Settings
FILE="/etc/apt/sources.list.d/kurento.list"
REPO="trusty-dev"  # KMS development - Ubuntu 14.04 (Trusty)

tee "$FILE" >/dev/null <<EOF
# Packages for Kurento Media Server
deb http://ubuntu.kurento.org ${REPO} kms6
EOF

gpg --list-public-keys --no-default-keyring --keyring /etc/apt/trusted.gpg \
    --with-colons | grep -q "Kurento" && RC=$? || RC=$?

if [ "$RC" -eq 1 ]; then
    wget http://ubuntu.kurento.org/kurento.gpg.key -O - | apt-key add -
elif [ "$RC" -ne 0 ]; then
    log "ERROR ($RC)"
    exit "$RC"
fi

apt-get update

log "Repository '$REPO' configured at $FILE"

# ------------

log "Done."
