#!/usr/bin/env bash
set -eu -o pipefail  # Abort on errors, disallow undefined variables
IFS=$'\n\t'          # Apply word splitting only on newlines and tabs

# Install every package related to Kurento Media Server.
#
# This script calls the other ones in order to install every package.
#
# Changes:
# 2018-03-16 Juan Navarro <juan.navarro@gmx.es>
# - Initial version.

# Check root permissions
[ "$(id -u)" -eq 0 ] || { echo "Please run as root"; exit 1; }

# Parse command line arguments
update=1
while getopts 'n' flag; do
  case "${flag}" in
    n) update=0 ;;
    *) ;;
  esac
done

(($update)) && apt-get update

# Set PATH so scripts can be called by name, without './'
BASEPATH="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"  # Absolute canonical path
PATH="$BASEPATH:${PATH:-}"

kurento-install-debugging-2018 -n
kurento-install-development -n
kurento-install-kms-2018 -n
kurento-install-packaging -n

echo "All packages installed successfully"

# ------------

echo "[$0] Done."
