#!/usr/bin/env bash
set -eu -o pipefail  # Abort on errors, disallow undefined variables
IFS=$'\n\t'          # Apply word splitting only on newlines and tabs

# Install debugging symbols for Kurento Media Server.
#
# Changes:
# 2018-02-12 Juan Navarro <juan.navarro@gmx.es>
# - Initial version (merged from other install scripts).
# - Add package: libsrtp1-dbg.
# 2018-03-16
# - Add command line argument parsing with 'getopts'.
# - Add argument '-n' to skip running `apt-get update`.
# 2018-03-23
# - Add log function.
# - FIXME for Trusty: openwebrtc-gst-plugins=0.10.0.20160909214034.trusty
# 2018-11-09 Fede Diaz <nordri@gmail.com>
# - Changed libnice package name libnice-dbg -> libnice10-dbgsym

# Set up logging function
BASENAME="$(basename "$0")"  # Complete file name
log() { echo "[$BASENAME] $*"; }

# Check root permissions
[ "$(id -u)" -eq 0 ] || { log "Please run as root"; exit 1; }

PACKAGES=(
    # Third-party libraries
    libglib2.0-0-dbg
    libssl1.0.0-dbg

    # Kurento external libraries
    #gstreamer1.5-plugins-base-dbg # FIXME - Workaround for Ubuntu 14.04 (Trusty)
    gstreamer1.5-plugins-good-dbg
    gstreamer1.5-plugins-ugly-dbg
    gstreamer1.5-plugins-bad-dbg
    gstreamer1.5-libav-dbg
    #libgstreamer1.5-0-dbg # FIXME - Workaround for Ubuntu 14.04 (Trusty)
    libnice10-dbgsym
    libsrtp1-dbg
    #openwebrtc-gst-plugins-dbg # FIXME - Workaround for Ubuntu 14.04 (Trusty)
    kmsjsoncpp-dbg

    # KMS main components
    kms-jsonrpc-dbg
    kms-core-dbg
    kms-elements-dbg
    kms-filters-dbg
    kurento-media-server-dbg

    # KMS extra modules
    kms-chroma-dbg
    kms-crowddetector-dbg
    kms-platedetector-dbg
    kms-pointerdetector-dbg
)

# FIXME - Workaround for Ubuntu 14.04 (Trusty)
if [ "$(lsb_release -sc)" = "trusty" ]; then
    PACKAGES+=(
        openwebrtc-gst-plugins=0.10.0.20160909214034.trusty
        openwebrtc-gst-plugins-dbg=0.10.0.20160909214034.trusty
    )
else
    PACKAGES+=(
        gstreamer1.5-plugins-base-dbg
        libgstreamer1.5-0-dbg
        openwebrtc-gst-plugins-dbg
    )
fi

# Parse command line arguments
update=1
while getopts 'n' flag; do
    case "${flag}" in
        n) update=0 ;;
        *) ;;
    esac
done

(( $update )) && apt-get update

apt-get install --yes "${PACKAGES[@]}"

log "All packages installed successfully"

# ------------

log "Done."
