#!/usr/bin/env bash
set -eu -o pipefail  # Abort on errors, disallow undefined variables
IFS=$'\n\t'          # Apply word splitting only on newlines and tabs

# Install packages needed to build Kurento Media Server.
#
# This script installs all development tools and pre-requisites that are needed
# to build a fresh copy of the Kurento Media Server source code. It does not
# install packages belonging to KMS itself.
#
# Notes:
# - gstreamer1.5-x is needed for the "timeoverlay" GStreamer plugin,
#   used by some tests in kms-elements.
#
# Changes:
# 2017-10-03 Juan Navarro <juan.navarro@gmx.es>
# - Initial version.
# 2018-02-02
# - Use a Bash Array to define all packages; run a single `apt-get` command.
# 2018-02-07
# - Add package: gstreamer1.5-tools.
# 2018-02-12
# - Move debugging packages to their own install script.
# 2018-02-25
# - Remove 'clang' and sort dev tools by name.
# 2018-03-16
# - Add command line argument parsing with 'getopts'.
# - Add argument '-n' to skip running `apt-get update`.
# 2018-03-23
# - Add log function.
# - FIXME for Trusty: openwebrtc-gst-plugins=0.10.0.20160909214034.trusty

# Set up logging function
BASENAME="$(basename "$0")"  # Complete file name
log() { echo "[$BASENAME] $*"; }

# Check root permissions
[ "$(id -u)" -eq 0 ] || { log "Please run as root"; exit 1; }

PACKAGES=(
    # Development tools
    build-essential
    cmake
    debhelper
    default-jdk
    gdb
    git
    maven
    pkg-config
    valgrind
    wget

    # 'maven-debian-helper' installs an old Maven version in Ubuntu 14.04 (Trusty),
    # so this ensures that the effective version is the one from 'maven'.
    maven-debian-helper-

    # System development libraries
    libboost-dev
    libboost-filesystem-dev
    libboost-log-dev
    libboost-program-options-dev
    libboost-regex-dev
    libboost-system-dev
    libboost-test-dev
    libboost-thread-dev
    libevent-dev
    libglib2.0-dev
    libglibmm-2.4-dev
    libopencv-dev
    libsigc++-2.0-dev
    libsoup2.4-dev
    libssl-dev
    libvpx-dev
    libxml2-utils
    uuid-dev

    # Kurento external libraries
    gstreamer1.5-plugins-base
    gstreamer1.5-plugins-good
    gstreamer1.5-plugins-ugly
    gstreamer1.5-plugins-bad
    gstreamer1.5-libav
    gstreamer1.5-nice
    gstreamer1.5-tools
    gstreamer1.5-x
    libgstreamer1.5-dev
    libgstreamer-plugins-base1.5-dev
    libnice-dev
    openh264-gst-plugins-bad-1.5
    #openwebrtc-gst-plugins-dev # FIXME - Workaround for Ubuntu 14.04 (Trusty)
    kmsjsoncpp-dev
    ffmpeg
)

# Parse command line arguments
update=1
while getopts 'n' flag; do
    case "${flag}" in
        n) update=0 ;;
        *) ;;
    esac
done

(( $update )) && apt-get update

apt-get install --yes "${PACKAGES[@]}"

# FIXME - Workaround for Ubuntu 14.04 (Trusty)
if [ "$(lsb_release -sc)" = "trusty" ]; then
    apt-get install --yes \
        openwebrtc-gst-plugins=0.10.0.20160909214034.trusty \
        openwebrtc-gst-plugins-dev=0.10.0.20160909214034.trusty \
    || apt-get install --yes \
        openwebrtc-gst-plugins=0.10.0.1.trusty~20180213160509.1.33ccf19 \
        openwebrtc-gst-plugins-dev=0.10.0.1.trusty~20180213160509.1.33ccf19
else
    apt-get install --yes \
        openwebrtc-gst-plugins-dev
fi

log "All packages installed successfully"

# ------------

log "Done."
