#!/usr/bin/env bash
set -eu -o pipefail  # Abort on errors, disallow undefined variables
IFS=$'\n\t'          # Apply word splitting only on newlines and tabs

# Install dependencies required for generating Debian packages from KMS modules.
#
# Notes:
# - flex will be automatically installed by gstreamer, but for now a bug in
#   package version detection prevents that.
# - libcommons-validator-java seems to be required to build "gstreamer" (it
#   failed with lots of errors from "jade", when building documentation files)
# - subversion (svn) is used in the Python build script (compile_project.py) due
#   to GitHub's lack of support for git-archive protocol
#   (https://github.com/isaacs/github/issues/554).
#
# Changes:
# 2017-10-03 Juan Navarro <juan.navarro@gmx.es>
# - Initial version.
# 2018-01-24
# - Add libcommons-validator-java
# 2018-02-02
# - Use a Bash Array to define all packages; run a single `apt-get` command.
# 2018-03-16
# - Add command line argument parsing with 'getopts'.
# - Add argument '-n' to skip running `apt-get update`.
# 2018-03-23
# - Add log function.

# Set up logging function
BASENAME="$(basename "$0")"  # Complete file name
log() { echo "[$BASENAME] $*"; }

# Check root permissions
[ $(id -u) -eq 0 ] || { log "Please run as root"; exit 1; }

PACKAGES=(
    # Packaging tools
    build-essential
    debhelper
    curl
    fakeroot
    flex
    git
    libcommons-validator-java
    python
    python-apt
    python-debian
    python-git
    python-requests
    python-yaml
    subversion
    wget
)

# Parse command line arguments
update=1
while getopts 'n' flag; do
    case "${flag}" in
        n) update=0 ;;
        *) ;;
    esac
done

(( $update )) && apt-get update

apt-get install --yes "${PACKAGES[@]}"

log "All packages installed successfully"

# ------------

log "Done."
