#!/usr/bin/env bash

# Install debugging symbols for Kurento Media Server.



# Shell setup
# -----------

BASEPATH="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"  # Absolute canonical path
# shellcheck source=bash.conf.sh
source "$BASEPATH/../bash.conf.sh" || {
    # Bash options for strict error checking
    set -o errexit -o errtrace -o pipefail -o nounset
}



# Check permissions
# -----------------

[[ "$(id -u)" -eq 0 ]] || {
    echo "ERROR: Please run as root user (or with 'sudo')"
    exit 1
}



# Ask for confirmation
# --------------------

echo "==== Install debug symbols for Kurento ===="
echo "This will add the Ubuntu 'dbgsym' repository sources"
IFS='' read -rs -n1 -p "Do you want to continue? [Y/n]" REPLY
echo ""
REGEX='^[Yy]?$'
[[ "$REPLY" =~ $REGEX ]] || exit 0



# Add Ubuntu 'dbgsym' repository sources
# --------------------------------------

if [[ -f /etc/upstream-release/lsb-release ]]; then
    source /etc/upstream-release/lsb-release
else
    source /etc/lsb-release
fi

tee /etc/apt/sources.list.d/ddebs.list >/dev/null <<EOF
# Packages with debug symbols
deb http://ddebs.ubuntu.com ${DISTRIB_CODENAME} main restricted universe multiverse
deb http://ddebs.ubuntu.com ${DISTRIB_CODENAME}-updates main restricted universe multiverse
deb http://ddebs.ubuntu.com ${DISTRIB_CODENAME}-proposed main restricted universe multiverse
EOF

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F2EDC64DC5AEE1F6B9C621F0C8CAB6595FDFF622



# Install debug symbols
# ---------------------

export DEBIAN_FRONTEND=noninteractive

PACKAGES=(
    # System libraries
    libc6-dbg  # Required for Valgrind
    libc6-dbgsym
    libglib2.0-0-dbg
    libglib2.0-0-dbgsym
    libssl1.0.0-dbg
    libssl1.0.0-dbgsym

    # Kurento 3rd-party libraries
    kmsjsoncpp-dbg
    libnice10-dbgsym
    libsrtp0-dbg
    libsrtp0-dbgsym
    libusrsctp-dbgsym
    openwebrtc-gst-plugins-dbg

    # GStreamer-1.0 (Ubuntu)
    libgstreamer1.0-0-dbg
    gstreamer1.0-libav-dbg
    gstreamer1.0-nice-dbgsym
    gstreamer1.0-plugins-bad-dbg
    gstreamer1.0-plugins-base-dbg
    gstreamer1.0-plugins-good-dbg
    gstreamer1.0-plugins-ugly-dbg

    # GStreamer-1.5 (Kurento)
    libgstreamer1.5-0-dbg
    gstreamer1.5-libav-dbg
    gstreamer1.5-nice-dbgsym
    gstreamer1.5-plugins-bad-dbg
    gstreamer1.5-plugins-base-dbg
    gstreamer1.5-plugins-good-dbg
    gstreamer1.5-plugins-ugly-dbg

    # Main packages
    kms-jsonrpc-dbg
    kms-core-dbg
    kms-elements-dbg
    kms-filters-dbg
    kurento-media-server-dbg

    # Extra packages
    #kms-chroma-dbg
    #kms-crowddetector-dbg
    #kms-platedetector-dbg
    #kms-pointerdetector-dbg
)

apt-get update

for PACKAGE in "${PACKAGES[@]}"; do
    apt-get install --no-install-recommends --yes "$PACKAGE" \
        || { echo "Skip unexisting"; }
done

echo "All packages installed successfully"
