/* Autogenerated with kurento-module-creator */

#ifndef __AR_MARKERDETECTOR_OPENCV_IMPL_HPP__
#define __AR_MARKERDETECTOR_OPENCV_IMPL_HPP__

#include <OpenCVProcess.hpp>
#include "ArMarkerdetector.hpp"
#include <EventHandler.hpp>
#include "Process.h"

namespace kurento
{
namespace module
{
namespace armarkerdetector
{

class ArMarkerdetectorOpenCVImpl : public virtual OpenCVProcess
{
protected:
  ArProcess ar;

public:

  ArMarkerdetectorOpenCVImpl ();

  virtual ~ArMarkerdetectorOpenCVImpl () {};

  virtual void process (cv::Mat &mat);

  void setShowDebugLevel (int showDebugLevel);
  int getShowDebugLevel ();
  void setOverlayImage (const std::string &overlayImage);
  std::string getOverlayImage ();
  void setOverlayText (const std::string &overlayText);
  std::string getOverlayText ();
  void setOverlayScale (float overlayScale);
  float getOverlayScale ();

};

} /* armarkerdetector */
} /* module */
} /* kurento */

#endif /*  __AR_MARKERDETECTOR_OPENCV_IMPL_HPP__ */
