/* Autogenerated with kurento-module-creator */

#ifndef __AR_MARKERDETECTOR_OPENCV_IMPL_HPP__
#define __AR_MARKERDETECTOR_OPENCV_IMPL_HPP__

#include <OpenCVProcess.hpp>
#include "ArMarkerdetector.hpp"
#include <EventHandler.hpp>

namespace kurento
{
namespace module
{
namespace armarkerdetector
{

class ArMarkerdetectorOpenCVImpl : public virtual OpenCVProcess
{

public:

  ArMarkerdetectorOpenCVImpl ();

  virtual ~ArMarkerdetectorOpenCVImpl () {};

  virtual void process (cv::Mat &mat);

  int getShowDebugLevel ();
  void setShowDebugLevel (int showDebugLevel);

  std::string getOverlayImage ();
  void setOverlayImage (const std::string &overlayImage);

  std::string getOverlayText ();
  void setOverlayText (const std::string &overlayText);

  float getOverlayScale ();
  void setOverlayScale (float overlayScale);

};

} /* armarkerdetector */
} /* module */
} /* kurento */

#endif /*  __AR_MARKERDETECTOR_OPENCV_IMPL_HPP__ */
