/* Autogenerated with kurento-module-creator */

#ifndef __CROWD_DETECTOR_FILTER_IMPL_HPP__
#define __CROWD_DETECTOR_FILTER_IMPL_HPP__

#include "FilterImpl.hpp"
#include "CrowdDetectorFilter.hpp"
#include <EventHandler.hpp>

namespace kurento
{

class MediaPipeline;
class RegionOfInterest;
class CrowdDetectorFilterImpl;

void Serialize (std::shared_ptr<CrowdDetectorFilterImpl> &object,
                JsonSerializer &serializer);

class CrowdDetectorFilterImpl : public FilterImpl,
  public virtual CrowdDetectorFilter
{

public:

  CrowdDetectorFilterImpl (const boost::property_tree::ptree &config,
                           std::shared_ptr<MediaPipeline> mediaPipeline,
                           const std::vector<std::shared_ptr<RegionOfInterest>> &rois);

  virtual ~CrowdDetectorFilterImpl ();

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType,
                        std::shared_ptr<EventHandler> handler);

  sigc::signal<void, CrowdDetectorFluidity> signalCrowdDetectorFluidity;
  sigc::signal<void, CrowdDetectorOccupancy> signalCrowdDetectorOccupancy;
  sigc::signal<void, CrowdDetectorDirection> signalCrowdDetectorDirection;

  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  GstElement *crowdDetector;
  gulong bus_handler_id;

  std::function<void (GstMessage *) > busMessageLambda;

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* kurento */

#endif /*  __CROWD_DETECTOR_FILTER_IMPL_HPP__ */
