/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include <FaceOverlayFilterImplFactory.hpp>
#include "FaceOverlayFilterImpl.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>
#include <gst/gst.h>

#define GST_CAT_DEFAULT kurento_face_overlay_filter_impl
GST_DEBUG_CATEGORY_STATIC (GST_CAT_DEFAULT);
#define GST_DEFAULT_NAME "KurentoFaceOverlayFilterImpl"

namespace kurento
{

FaceOverlayFilterImpl::FaceOverlayFilterImpl (std::shared_ptr<MediaPipeline>
    mediaPipeline) : FilterImpl (
        std::dynamic_pointer_cast<MediaObjectImpl> ( mediaPipeline) )
{
  // FIXME: Implement this
}

void FaceOverlayFilterImpl::unsetOverlayedImage ()
{
  // FIXME: Implement this
  throw KurentoException (NOT_IMPLEMENTED,
                          "FaceOverlayFilterImpl::unsetOverlayedImage: Not implemented");
}

void FaceOverlayFilterImpl::setOverlayedImage (const std::string &uri,
    float offsetXPercent, float offsetYPercent, float widthPercent,
    float heightPercent)
{
  // FIXME: Implement this
  throw KurentoException (NOT_IMPLEMENTED,
                          "FaceOverlayFilterImpl::setOverlayedImage: Not implemented");
}

MediaObjectImpl *
FaceOverlayFilterImplFactory::createObject (std::shared_ptr<MediaPipeline>
    mediaPipeline) const
{
  return new FaceOverlayFilterImpl (mediaPipeline);
}

FaceOverlayFilterImpl::StaticConstructor
FaceOverlayFilterImpl::staticConstructor;

FaceOverlayFilterImpl::StaticConstructor::StaticConstructor()
{
  GST_DEBUG_CATEGORY_INIT (GST_CAT_DEFAULT, GST_DEFAULT_NAME, 0,
                           GST_DEFAULT_NAME);
}

} /* kurento */
