/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include <GStreamerFilterImplFactory.hpp>
#include "GStreamerFilterImpl.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>
#include <gst/gst.h>

#define GST_CAT_DEFAULT kurento_gstreamer_filter_impl
GST_DEBUG_CATEGORY_STATIC (GST_CAT_DEFAULT);
#define GST_DEFAULT_NAME "KurentoGStreamerFilterImpl"

namespace kurento
{

GStreamerFilterImpl::GStreamerFilterImpl (std::shared_ptr<MediaPipeline>
    mediaPipeline, const std::string &command) : FilterImpl (
        std::dynamic_pointer_cast<MediaObjectImpl> ( mediaPipeline) )
{
  // FIXME: Implement this
}

MediaObjectImpl *
GStreamerFilterImplFactory::createObject (std::shared_ptr<MediaPipeline>
    mediaPipeline, const std::string &command) const
{
  return new GStreamerFilterImpl (mediaPipeline, command);
}

GStreamerFilterImpl::StaticConstructor GStreamerFilterImpl::staticConstructor;

GStreamerFilterImpl::StaticConstructor::StaticConstructor()
{
  GST_DEBUG_CATEGORY_INIT (GST_CAT_DEFAULT, GST_DEFAULT_NAME, 0,
                           GST_DEFAULT_NAME);
}

} /* kurento */
