/* Autogenerated with kurento-module-creator */

#ifndef __KMS_DETECT_FACES_IMPL_HPP__
#define __KMS_DETECT_FACES_IMPL_HPP__

#include "FilterImpl.hpp"
#include "KmsDetectFaces.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace datachannelexample
{
class KmsDetectFacesImpl;
} /* datachannelexample */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (
  std::shared_ptr<kurento::module::datachannelexample::KmsDetectFacesImpl>
  &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace datachannelexample
{

class KmsDetectFacesImpl : public FilterImpl, public virtual KmsDetectFaces
{

public:

  KmsDetectFacesImpl (const boost::property_tree::ptree &config,
                      std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~KmsDetectFacesImpl () {};

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType,
                        std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:
  GstElement *faceDetector = NULL;

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* datachannelexample */
} /* module */
} /* kurento */

#endif /*  __KMS_DETECT_FACES_IMPL_HPP__ */
