/* Autogenerated with kurento-module-creator */

#ifndef __KMS_SHOW_FACES_IMPL_HPP__
#define __KMS_SHOW_FACES_IMPL_HPP__

#include "FilterImpl.hpp"
#include "KmsShowFaces.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace datachannelexample
{
class KmsShowFacesImpl;
} /* datachannelexample */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (
  std::shared_ptr<kurento::module::datachannelexample::KmsShowFacesImpl> &object,
  JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace datachannelexample
{

class KmsShowFacesImpl : public FilterImpl, public virtual KmsShowFaces
{

public:

  KmsShowFacesImpl (const boost::property_tree::ptree &config,
                    std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~KmsShowFacesImpl () {};

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType,
                        std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:
  GstElement *imageOverlay = NULL;

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* datachannelexample */
} /* module */
} /* kurento */

#endif /*  __KMS_SHOW_FACES_IMPL_HPP__ */
