/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include <OpencvPluginSampleImplFactory.hpp>
#include "OpencvPluginSampleImpl.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>
#include "MediaPipelineImpl.hpp"

#define GST_CAT_DEFAULT kurento_opencv_plugin_sample_impl
GST_DEBUG_CATEGORY_STATIC (GST_CAT_DEFAULT);
#define GST_DEFAULT_NAME "KurentoOpencvPluginSampleImpl"

namespace kurento
{
namespace module
{
namespace opencvpluginsample
{

OpencvPluginSampleImpl::OpencvPluginSampleImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline) : OpenCVFilterImpl (config, std::dynamic_pointer_cast<MediaPipelineImpl> (mediaPipeline) )

{
}

void OpencvPluginSampleImpl::setFilterType (int filterType)
{
  OpencvPluginSampleOpenCVImpl::setFilterType (filterType);
}

void OpencvPluginSampleImpl::setEdgeThreshold (int edgeValue)
{
  OpencvPluginSampleOpenCVImpl::setEdgeThreshold (edgeValue);
}

MediaObjectImpl *
OpencvPluginSampleImplFactory::createObject (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline) const
{
  return new OpencvPluginSampleImpl (config, mediaPipeline);
}

OpencvPluginSampleImpl::StaticConstructor OpencvPluginSampleImpl::staticConstructor;

OpencvPluginSampleImpl::StaticConstructor::StaticConstructor()
{
  GST_DEBUG_CATEGORY_INIT (GST_CAT_DEFAULT, GST_DEFAULT_NAME, 0,
                           GST_DEFAULT_NAME);
}

} /* opencvpluginsample */
} /* module */
} /* kurento */
