/* Autogenerated with kurento-module-creator */

#ifndef __SAMPLE_PLUGIN_FILTER_IMPL_HPP__
#define __SAMPLE_PLUGIN_FILTER_IMPL_HPP__

#include "FilterImpl.hpp"
#include "SamplePluginFilter.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace sampleplugin
{
class SamplePluginFilterImpl;
} /* sampleplugin */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::sampleplugin::SamplePluginFilterImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace sampleplugin
{

class SamplePluginFilterImpl : public FilterImpl, public virtual SamplePluginFilter
{

public:

  SamplePluginFilterImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~SamplePluginFilterImpl () {};

  void setFilterType (int filterType);
  void setEdgeThreshold (int edgeValue);

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* sampleplugin */
} /* module */
} /* kurento */

#endif /*  __SAMPLE_PLUGIN_FILTER_IMPL_HPP__ */
