/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include <ZBarFilterImplFactory.hpp>
#include "ZBarFilterImpl.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>
#include <gst/gst.h>

#define GST_CAT_DEFAULT kurento_zbar_filter_impl
GST_DEBUG_CATEGORY_STATIC (GST_CAT_DEFAULT);
#define GST_DEFAULT_NAME "KurentoZBarFilterImpl"

namespace kurento
{

ZBarFilterImpl::ZBarFilterImpl (std::shared_ptr<MediaPipeline> mediaPipeline) :
  FilterImpl (std::dynamic_pointer_cast<MediaObjectImpl> ( mediaPipeline) )
{
  // FIXME: Implement this
}

MediaObjectImpl *
ZBarFilterImplFactory::createObject (std::shared_ptr<MediaPipeline>
                                     mediaPipeline) const
{
  return new ZBarFilterImpl (mediaPipeline);
}

ZBarFilterImpl::StaticConstructor ZBarFilterImpl::staticConstructor;

ZBarFilterImpl::StaticConstructor::StaticConstructor()
{
  GST_DEBUG_CATEGORY_INIT (GST_CAT_DEFAULT, GST_DEFAULT_NAME, 0,
                           GST_DEFAULT_NAME);
}

} /* kurento */
