${event.name}.cpp
/* Autogenerated with Kurento Idl */

#include "${event.name}.hpp"
#include <JsonSerializer.hpp>
<#list event.properties as property>
<#if model.remoteClasses?seq_contains(property.type.type) || 
  model.complexTypes?seq_contains(property.type.type) || 
  model.events?seq_contains(property.type.type)>
#include "${property.type.name}.hpp"
</#if>
</#list>

void
Serialize(std::shared_ptr<kurento::${event.name}>& object, JsonSerializer& s)
{
  if (!s.IsWriter && !object) {
    object.reset(new kurento::${event.name}());
  }

  if (object) {
  <#if event.extends??><#rt><#lt>
    std::shared_ptr<kurento::${event.extends.name}> parent;

  </#if>
  <#list event.properties as property>
    s.Serialize("${property.name}", object->${property.name});
  </#list>
  <#if event.extends??>
    parent = std::dynamic_pointer_cast<kurento::${event.extends.name}> (object);

    if (parent) {
      Serialize(parent, s);
    }

  </#if>
  }
}
