<#if module.complexTypes?? && module.complexTypes?has_content>
complexTypes/index.js
/* Autogenerated with Kurento Idl */

  <#include "license.ftm" >

/**
 * Media API for the Kurento Web SDK
 *
 * @module ${module.name}/complexTypes
 *
 * @copyright 2013-2014 Kurento (http://kurento.org/)
 * @license LGPL
 */

  <#list module.complexTypes?sort_by("name") as complexType>
var ${complexType.name} = require('./${complexType.name}');
  </#list>


  <#list module.complexTypes?sort_by("name") as complexType>
exports.${complexType.name} = ${complexType.name};
  </#list>
</#if>
