<#if module.events?? && module.events?has_content>
  <#include "macros.ftm" >
  <#assign module_name=module.name>
events.js
/* Autogenerated with Kurento Idl */

  <#include "license.ftm" >

  <#list module.events?sort_by("name") as event>

/**
  <#if event.doc??>
    <#list event.doc?split("\n") as line>
 * ${sphinxLinks(line, module_name)}
    </#list>
 *
  </#if>
 * @event module:${module_name}#${event.name}
  <#if event.properties?? && event.properties?has_content>
  <#if event.extends??>
 *
 * @type {module:${module_name}#event:${event.extends.name}}
  </#if>
 *
    <#list event.properties as property>
 * @property {${namepath(property.type.name)}} ${property.name}
      <#if property.doc??>
        <#list property.doc?split("\n") as line>
 *  ${sphinxLinks(line, module_name)}
        </#list>
      </#if>
    </#list>
  </#if>
 */
  </#list>
</#if>
