#!/usr/bin/env bash

#/
#/ Generate and commit source files for Read The Docs.
#/
#/ Arguments:
#/
#/   None.
#/

# ------------ Shell setup ------------

# Shell options for strict error checking
set -o errexit -o errtrace -o pipefail -o nounset

# Enable debug mode
set -o xtrace

# Logging functions
BASENAME="$(basename "$0")"  # Complete file name
log()   { echo "[${BASENAME}] $*"; }
error() { echo "[${BASENAME}] ERROR $*"; exit 1; }

# Trap functions
on_error() { ERROR=1; }
trap on_error ERR
on_exit() { (( ${ERROR-${?}} )) && error || log "SUCCESS"; }
trap on_exit EXIT

# Print help message
usage() { grep '^#/' "$0" | cut -c 4-; exit 0; }
expr match "${1-}" '^\(-h\|--help\)$' >/dev/null && usage



# ------------ Script start ------------

log "############ RUN: [$0] ############"

# Internal variables
RTD_PROJECT="${KURENTO_PROJECT}-readthedocs"

kurento_clone_repo.sh "$KURENTO_PROJECT" \
|| error "Command failed: kurento_clone_repo $KURENTO_PROJECT"

{
    pushd "$KURENTO_PROJECT"

    if [ -z "${MAVEN_SETTINGS:+x}" ]; then
        cp Makefile Makefile.ci
    else
        sed -e "s/mvn/mvn --settings $MAVEN_SETTINGS/g" Makefile > Makefile.ci
    fi

    make --file="Makefile.ci" ci-readthedocs \
    || error "Command failed: make ci-readthedocs"

    rm Makefile.ci

    popd  # $KURENTO_PROJECT
}

log "Command: kurento_check_version (tagging enabled)"
kurento_check_version.sh true \
|| error "Command failed: kurento_check_version (tagging enabled)"

kurento_clone_repo.sh "$RTD_PROJECT" \
|| error "Command failed: kurento_clone_repo $RTD_PROJECT"

rm -rf "${RTD_PROJECT}/*"
cp -a "${KURENTO_PROJECT}/*" "${RTD_PROJECT}/"

log "Commit and push changes to repo: $RTD_PROJECT"

{
    pushd "$RTD_PROJECT"

    git status
    git diff-index --quiet HEAD || {
      git add --all .
      log "TODO REVIEW: global GIT_COMMIT: ${GIT_COMMIT}"
      git commit -m "Code autogenerated from Kurento/${KURENTO_PROJECT}@${GIT_COMMIT}"
      git push origin master \
      || error "Command failed: git push ($RTD_PROJECT)"
    }

    export CHECK_SUBMODULES="no"
    log "Command: kurento_check_version (tagging enabled)"
    kurento_check_version.sh true \
    || error "Command failed: kurento_check_version (tagging enabled)"

    popd  # $RTD_PROJECT
}
