#!/bin/bash -x
# PARAM API
#  dist
#       Distribution where package is uploaded
#  comp
#      Component where package is uploaded. Component main is assigned
#      if this parameter is not provided
#  name
#      Name of file given to package
#
# Get dist param from query string
DIST=$(echo $QUERY_STRING | grep 'dist=' | sed 's/QUERY_STRING=//g' | sed 's/^.*dist=\([^\&]*\).*$/\1/g')
COMP=$(echo $QUERY_STRING | grep 'comp=' | sed 's/QUERY_STRING=//g' | sed 's/^.*comp=\([^\&]*\).*$/\1/g')
NAME=$(echo $QUERY_STRING | grep 'name=' | sed 's/QUERY_STRING=//g' | sed 's/^.*name=\([^\&]*\).*$/\1/g')


if [ -z "$DIST" -o -z "$COMP" ]; then
    STATUS="Status: 400 Bad Request"
    TITLE="400 Bad Request"
    BODY="<h1>MISSING PARAMETERS</h1><p>Parameters dist & comp must be provided for package upload"
else
    mkdir -p /tmp/$DIST/$COMP
    UPLOAD_FILE=$([ -n "$NAME" ] && echo /tmp/$DIST/$COMP/$NAME || mktemp --suffix .deb)
    cat - > $UPLOAD_FILE
    echo "Upload to reprepro" > $UPLOAD_FILE.reprepro.msg
    reprepro -b .. --waitforlock 10 -C $COMP includedeb $DIST $UPLOAD_FILE >> $UPLOAD_FILE.reprepro.msg 2>&1
    reprepro_res=$?
    echo "Upload to aptly" > $UPLOAD_FILE.aptly.msg
    # Requires package task-spooler
    tsp -C
    tsp aptly repo add $DIST $UPLOAD_FILE >> $UPLOAD_FILE.aptly.msg 2>&1
    tsp rm -f $UPLOAD_FILE >> $UPLOAD_FILE.aptly.msg 2>&1
    # Delete scheduled updates before inserting new one
    for task in $(tsp | egrep '(queued|running)' | grep "aptly publish update $DIST s3:ubuntu:" | awk '{print $1}'); do
      tsp -r $task
    done
    tsp aptly publish update $DIST s3:ubuntu: >> $UPLOAD_FILE.aptly.msg 2>&1
    aptly_res=$?
    if [ $reprepro_res -eq 0 -a $aptly_res -eq 0 ]; then
        STATUS="Status: 200 OK"
        TITLE="REQUEST ACCEPTED"
    else
        STATUS="Status: 500 OK"
        TITLE="500 Internal Server ERROR"
    fi
    BODY=$(cat $UPLOAD_FILE.reprepro.msg)
    BODY=$BODY$(echo '')
    BODY=$BODY$(cat $UPLOAD_FILE.aptly.msg)
    rm -f $UPLOAD_FILE.*
fi
echo $STATUS
echo "Content-type: text/html"
echo ""
echo "<html>"
echo "<head>"
echo "<title>$TITLE</title>"
echo "</head>"
echo "<body>"
echo "$BODY"
echo "</body>"
echo "</html>"
