${module.name}Dependencies.cmake
# Autogenerated with kurento-module-creator
cmake_minimum_required(VERSION 2.8)

find_package(Boost REQUIRED)

find_package(PkgConfig)

###############################################################
# Dependencies
###############################################################
<#if !module.imports[0]??>
find_package(KmsJsonRpc REQUIRED ^0.1.0)
pkg_check_modules(GSTREAMER REQUIRED gstreamer-1.0>=1.3.3)
pkg_check_modules(SIGCPP REQUIRED sigc++-2.0>=2.0.10)
pkg_check_modules(GLIBMM REQUIRED glibmm-2.4>=2.37)
</#if>
<#list module.imports as import>
# looking for ${import.name} dependencies
pkg_check_modules(${import.module.code.implementation.lib?replace("lib", "")?upper_case} REQUIRED ${import.module.code.implementation.lib?replace("lib", "")}>=${import.version})
</#list>

set (DEPENDENCIES_LIBRARIES
<#if !module.imports[0]??>
  <#noparse>${GSTREAMER_LIBRARIES}</#noparse>
  <#noparse>${KmsJsonRpc_LIBRARIES}</#noparse>
  <#noparse>${SIGCPP_LIBRARIES}</#noparse>
  <#noparse>${GLIBMM_LIBRARIES}</#noparse>
</#if>
<#list module.imports as import>
  <#noparse>${</#noparse>${import.module.code.implementation.lib?replace("lib", "")?upper_case}_LIBRARIES<#noparse>}</#noparse>
</#list>
  CACHE INTERNAL "Model library dependencies"
)

set (DEPENDENCIES_INCLUDE_DIRS
<#if !module.imports[0]??>
  <#noparse>${GSTREAMER_INCLUDE_DIRS}</#noparse>
  <#noparse>${KmsJsonRpc_INCLUDE_DIRS}</#noparse>
  <#noparse>${SIGCPP_INCLUDE_DIRS}</#noparse>
  <#noparse>${GLIBMM_INCLUDE_DIRS}</#noparse>
</#if>
<#list module.imports as import>
  <#noparse>${</#noparse>${import.module.code.implementation.lib?replace("lib", "")?upper_case}_INCLUDE_DIRS<#noparse>}</#noparse>
</#list>
  CACHE INTERNAL "Model library dependencies"
)
