/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */

var checkType = require('../checkType');

/**
 * Media API for the Kurento Web SDK
 *
 * @module KwsMedia/complexTypes
 *
 * @copyright 2014 Kurento (http://kurento.org/)
 * @license LGPL
 */

/**
 * Checker for {@link KwsMedia/complexTypes~Point}
 *
 * @param {String} key
 * @param {KwsMedia/complexTypes~Point} value
 */
function checkPoint(key, value)
{
  checkType('int', key+'.x', value.x, true);
  checkType('int', key+'.y', value.y, true);
};


/**
 * Point in a physical screen, coordinates are in pixels with X left to right and Y top to down.
 *
 * @typedef KwsMedia/complexTypes~Point
 *
 * @type {Object}
 * @property {int} x - X coordinate in pixels of a point in the screen
 * @property {int} y - Y coordinate in pixels of a point in the screen
 */


module.exports = checkPoint;
