/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */

var checkType = require('../checkType');

/**
 * Media API for the Kurento Web SDK
 *
 * @module KwsMedia/complexTypes
 *
 * @copyright 2014 Kurento (http://kurento.org/)
 * @license LGPL
 */

/**
 * Checker for {@link KwsMedia/complexTypes~RegionOfInterest}
 *
 * @param {String} key
 * @param {KwsMedia/complexTypes~RegionOfInterest} value
 */
function checkRegionOfInterest(key, value)
{
  checkType('RelativePoint', key+'.points', value.points, true);
  checkType('RegionOfInterestConfig', key+'.regionOfInterestConfig', value.regionOfInterestConfig, true);
  checkType('String', key+'.id', value.id, true);
};


/**
 * Region of interest for some events in a video processing filter
 *
 * @typedef KwsMedia/complexTypes~RegionOfInterest
 *
 * @type {Object}
 * @property {RelativePoint} points - list of points delimiting the region of interest
 * @property {RegionOfInterestConfig} regionOfInterestConfig - data structure for configuration of CrowdDetector regions of interest
 * @property {String} id - identifier of the region of interest. The string used for the id must begin 
 with a letter followed by an alphanumeric character included (/-_.:+)
 */


module.exports = checkRegionOfInterest;
