/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */

var checkType = require('../checkType');

/**
 * Media API for the Kurento Web SDK
 *
 * @module KwsMedia/complexTypes
 *
 * @copyright 2014 Kurento (http://kurento.org/)
 * @license LGPL
 */

/**
 * Checker for {@link KwsMedia/complexTypes~RelativePoint}
 *
 * @param {String} key
 * @param {KwsMedia/complexTypes~RelativePoint} value
 */
function checkRelativePoint(key, value)
{
  checkType('float', key+'.x', value.x, true);
  checkType('float', key+'.y', value.y, true);
};


/**
 * Relative points in a physical screen, values are a percentage relative to the image dimensions. X left to right and Y top to down.
 *
 * @typedef KwsMedia/complexTypes~RelativePoint
 *
 * @type {Object}
 * @property {float} x - Percentage relative to the image width to calculate the X coordinate of the point [0..1]
 * @property {float} y - Percentage relative to the image height to calculate the Y coordinate of the point [0..1]
 */


module.exports = checkRelativePoint;
