/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */

var checkType = require('../checkType');

/**
 * Media API for the Kurento Web SDK
 *
 * @module KwsMedia/complexTypes
 *
 * @copyright 2014 Kurento (http://kurento.org/)
 * @license LGPL
 */

/**
 * Checker for {@link KwsMedia/complexTypes~WindowParam}
 *
 * @param {String} key
 * @param {KwsMedia/complexTypes~WindowParam} value
 */
function checkWindowParam(key, value)
{
  checkType('int', key+'.topRightCornerX', value.topRightCornerX, true);
  checkType('int', key+'.topRightCornerY', value.topRightCornerY, true);
  checkType('int', key+'.width', value.width, true);
  checkType('int', key+'.height', value.height, true);
};


/**
 * Parameter representing a window in a video stream.
It is used in command and constructors for media elements.

All units are in pixels, X runs from left to right, Y from top to bottom.
 *
 * @typedef KwsMedia/complexTypes~WindowParam
 *
 * @type {Object}
 * @property {int} topRightCornerX - X coordinate of the left upper point of the window
 * @property {int} topRightCornerY - Y coordinate of the left upper point of the window
 * @property {int} width - width in pixels of the window
 * @property {int} height - height in pixels of the window
 */


module.exports = checkWindowParam;
