<#assign node_name=module.code.api.js.nodeName>
README.md
${node_name}
============
${module.code.api.js.npmDescription}

This code is the autogenerated javascript client for [kurento] module ${module.name}.

[kurento]: http://www.kurento.org
