#!/usr/bin/env bash
set -eu -o pipefail  # Abort on errors, disallow undefined variables
IFS=$'\n\t'          # Apply word splitting only on newlines and tabs

# Clone all Git repos related to Kurento forked libraries.
#
# Changes:
# 2018-02-09 Juan Navarro <juan.navarro@gmx.es>
# - Initial version.
# 2018-02-13
# - Print the list of repos that will get cloned.
# - Don't hide stderr from `git clone`.
# 2018-03-23
# - Add log function.

# Set up logging function
BASENAME="$(basename "$0")"  # Complete file name
log() { echo "[$BASENAME] $*"; }

# Settings
# BASE_URL="https://github.com/Kurento"  # Use HTTPS (Username + Password)
BASE_URL="git@github.com:Kurento"  # Use SSH (Public/Private SSH Keys)

REPOS=(
    jsoncpp
    libsrtp
    openh264
    usrsctp
    gstreamer
    gst-plugins-base
    gst-plugins-good
    gst-plugins-bad
    gst-plugins-ugly
    gst-libav
    openwebrtc-gst-plugins
    libnice
)

log "==== Clone Git repositories ===="
log "This script will clone all Kurento Forked repos:"
printf '%s\n' "${REPOS[@]}"
read -p "Are you sure? Type 'yes': " -r SURE
[ "$SURE" != "yes" ] && [ "$SURE" != "YES" ] && { log "Aborting"; exit 1; }

log "Working..."

for REPO in "${REPOS[@]}"; do
    REPO_URL="${BASE_URL}/${REPO}.git"
    if [ -d "$REPO" ]; then
        log "Skip already existing: $REPO"
    else
        log "Clone repository: $REPO"
        git clone "$REPO_URL" >/dev/null
    fi
done

log "Git repositories cloned at ${PWD}/"

# ------------

log "Done."
