#!/usr/bin/env bash
set -eu -o pipefail  # Abort on errors, disallow undefined variables
IFS=$'\n\t'          # Apply word splitting only on newlines and tabs

# Install Kurento Media Server packages for users and developers.
#
# This script installs all KMS packages, together with their corresponding
# development libraries. and the tools used to write new modules (module
# creator, CMake utils). It does not include the debugging symbols, which can be
# installed with a separate script.
#
# Notes:
# - gstreamer1.5-x is needed for the "timeoverlay" GStreamer plugin,
#   used by some tests in kms-elements.
#
# Changes:
# 2018-02-08 Juan Navarro <juan.navarro@gmx.es>
# - Initial version.
# 2018-02-12
# - Moved debugging packages to their own install script.
# 2018-03-16
# - Add command line argument parsing with 'getopts'.
# - Add argument '-n' to skip running `apt-get update`.
# 2018-03-23
# - Add log function.

# Set up logging function
BASENAME="$(basename "$0")"  # Complete file name
log() { echo "[$BASENAME] $*"; }

# Check root permissions
[ "$(id -u)" -eq 0 ] || { log "Please run as root"; exit 1; }

PACKAGES=(
    # KMS main components
    kurento-module-creator-4.0
    kms-cmake-utils
    kms-jsonrpc-1.0
    kms-jsonrpc-1.0-dev
    kms-core-6.0
    kms-core-6.0-dev
    kms-elements-6.0
    kms-elements-6.0-dev
    kms-filters-6.0
    kms-filters-6.0-dev
    kurento-media-server-6.0
    kurento-media-server-6.0-dev

    # KMS extra modules
    kms-chroma-6.0
    kms-chroma-6.0-dev
    kms-crowddetector-6.0
    kms-crowddetector-6.0-dev
    kms-datachannelexample
    kms-datachannelexample-dev
    kms-platedetector-6.0
    kms-platedetector-6.0-dev
    kms-pointerdetector-6.0
    kms-pointerdetector-6.0-dev

    # Optional but recommended packages
    openh264-gst-plugins-bad-1.5
)

# Parse command line arguments
update=1
while getopts 'n' flag; do
    case "${flag}" in
        n) update=0 ;;
        *) ;;
    esac
done

(( $update )) && apt-get update

apt-get install --yes "${PACKAGES[@]}"

log "All packages installed successfully"

# ------------

log "Done."
