#!/usr/bin/env bash
set -eu -o pipefail  # Abort on errors, disallow undefined variables
IFS=$'\n\t'          # Apply word splitting only on newlines and tabs

# Clone all Git repos related to Kurento Media Server.
#
# Changes:
# 2018-01-24 Juan Navarro <juan.navarro@gmx.es>
# - Initial version.
# 2018-02-02
# - Use a Bash Array to define all repos.
# 2018-02-13
# - Print the list of repos that will get cloned.
# - Don't hide stderr from `git clone`.
# 2018-03-23
# - Add log function.

# Set up logging function
BASENAME="$(basename "$0")"  # Complete file name
log() { echo "[$BASENAME] $*"; }

# Settings
# BASE_URL="https://github.com/Kurento"  # Use HTTPS (Username + Password)
BASE_URL="git@github.com:Kurento"  # Use SSH (Public/Private SSH Keys)

REPOS=(
    # KMS main components
    kms-omni-build
    kurento-module-creator
    kms-cmake-utils
    kms-jsonrpc
    kms-core
    kms-elements
    kms-filters
    kurento-media-server

    # KMS extra modules
    kms-chroma
    kms-crowddetector
    kms-datachannelexample
    kms-platedetector
    kms-pointerdetector

    # Additional sample modules
    kms-markerdetector
    kms-opencv-plugin-sample
    kms-plugin-sample

    # Tools and documentation
    adm-scripts
    bugtracker
    doc-kurento
    kurento-docker

    # Client applications - Java
    kurento-maven-plugin
    kurento-qa-pom
    kurento-java
    kurento-tutorial-java
    kurento-tutorial-test

    # Client applications - JavaScript & Node
    kurento-jsonrpc-js
    kurento-utils-js
    kurento-client-js
    kurento-tutorial-js
    kurento-tutorial-node

    # Miscellaneous experiments
    experiments
    kurento-demos-java
)

log "==== Clone Git repositories ===="
log "This script will clone all Kurento repos:"
printf '%s\n' "${REPOS[@]}"
read -p "Are you sure? Type 'yes': " -r SURE
[ "$SURE" != "yes" ] && [ "$SURE" != "YES" ] && { log "Aborting"; exit 1; }

log "Working..."

for REPO in "${REPOS[@]}"; do
    REPO_URL="${BASE_URL}/${REPO}.git"
    if [ -d "$REPO" ]; then
        log "Skip already existing: $REPO"
    else
        log "Clone repository: $REPO"
        git clone "$REPO_URL" >/dev/null
    fi
done

log "Git repositories cloned at ${PWD}/"

# ------------

log "Done."
