#!/usr/bin/env bash
set -eu -o pipefail  # Abort on errors, disallow undefined variables
IFS=$'\n\t'          # Apply word splitting only on newlines and tabs

# Configure the Kurento packages repository for `apt-get`.
#
# Changes:
# 2019-02-14 Fede Diaz <nordri@gmail.com>
# - New version for Ubuntu Bionic (18.04)

# Set up logging function
BASENAME="$(basename "$0")"  # Complete file name
log() { echo "[$BASENAME] $*"; }

# Check root permissions
[ "$(id -u)" -eq 0 ] || { log "Please run as root"; exit 1; }

# Settings
FILE="/etc/apt/sources.list.d/kurento.list"
DISTRO="bionic"  # KMS for Ubuntu 18.04 (Bionic)

apt-get update && apt-get install -y gnupg2
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5AFA7A83

tee "$FILE" >/dev/null <<EOF
# Kurento Media Server - Pre-Release packages
deb [arch=amd64] http://ubuntu.openvidu.io/dev $DISTRO kms6
EOF

apt-get update

# ------------

log "Done."
