<#if module.events?? && module.events?has_content>
  <#include "macros.ftm" >
  <#assign module_name=module.name>
events.js
/* Autogenerated with Kurento Idl */

  <#include "license.ftm" >

  <#list module.events?sort_by("name") as event>

/**
  <#if event.doc??>
    <@docstring doc=event.doc namepath=module_name/>
 *
  </#if>
 * @event module:${module_name}#${event.name}
  <#if event.properties?? && event.properties?has_content>
  <#if event.extends??>
 *
 * @type {module:${module_name}#event:${event.extends.name}}
  </#if>
 *
    <#list event.properties as property>
 * @property {${namepath(property.type.name)}} ${property.name}
      <@docstring doc=property.doc namepath=module_name indent=1/>
    </#list>
  </#if>
 */
  </#list>
</#if>
