index.js
/* Autogenerated with Kurento Idl */

<#include "license.ftm" >

/**
 * Media API for the Kurento Web SDK
 *
 * @module ${module.name}
 *
 * @copyright 2013-2015 Kurento (http://kurento.org/)
 * @license ALv2
 */

Object.defineProperty(exports, 'name',    {value: '${module.name}'});
Object.defineProperty(exports, 'version', {value: '${module.version}'});


<#list module.remoteClasses?sort_by("name") as remoteClass>
  <#if !remoteClass.abstract>
var ${remoteClass.name} = require('./${remoteClass.name}');
  </#if>
</#list>


<#assign remoteClasses_abstract=false>
<#list module.remoteClasses?sort_by("name") as remoteClass>
  <#if remoteClass.abstract>
    <#assign remoteClasses_abstract=true>
  <#else>
exports.${remoteClass.name} = ${remoteClass.name};
  </#if>
</#list>
<#assign complexTypes=module.complexTypes?? && module.complexTypes?has_content>
<#if remoteClasses_abstract || complexTypes>

  <#if remoteClasses_abstract>
exports.abstracts <#if complexTypes>   </#if>= require('./abstracts');
  </#if>
  <#if complexTypes>
exports.complexTypes = require('./complexTypes');
  </#if>
</#if>
