<#assign remoteClasses_abstract=[]>
<#list module.remoteClasses?sort_by("name") as remoteClass>
  <#if remoteClass.abstract>
    <#assign remoteClasses_abstract=remoteClasses_abstract+[remoteClass.name]>
  </#if>
</#list>
<#if remoteClasses_abstract?has_content>
abstracts/index.js
/* Autogenerated with Kurento Idl */

  <#include "license.ftm" >

/**
 * Media API for the Kurento Web SDK
 *
 * @module ${module.name}/abstracts
 *
 * @copyright 2013-2015 Kurento (http://kurento.org/)
 * @license ALv2
 */

  <#list remoteClasses_abstract as remoteClass_name>
var ${remoteClass_name} = require('./${remoteClass_name}');
  </#list>


  <#list remoteClasses_abstract as remoteClass_name>
exports.${remoteClass_name} = ${remoteClass_name};
  </#list>
</#if>
