<#if module.complexTypes?? && module.complexTypes?has_content
  || module.name == 'core'>
complexTypes/index.js
/* Autogenerated with Kurento Idl */

  <#include "license.ftm" >

/**
 * Media API for the Kurento Web SDK
 *
 * @module ${module.name}/complexTypes
 *
 * @copyright 2013-2015 Kurento (http://kurento.org/)
 * @license ALv2
 */

  <#if module.name == 'core'>
var ComplexType = require('./ComplexType');

  </#if>
  <#list module.complexTypes?sort_by("name") as complexType>
var ${complexType.name} = require('./${complexType.name}');
  </#list>


  <#if module.name == 'core'>
exports.ComplexType = ComplexType;

  </#if>
  <#list module.complexTypes?sort_by("name") as complexType>
exports.${complexType.name} = ${complexType.name};
  </#list>
</#if>
