cpp/${remoteClass.name}.hpp
/* Autogenerated with Kurento Idl */

#ifndef __${camelToUnderscore(remoteClass.name)}_HPP__
#define __${camelToUnderscore(remoteClass.name)}_HPP__

#include <jsoncpp/json/json.h>
#include <JsonRpcException.hpp>
#include <memory>

<#if (remoteClass.extends)??>
#include "${remoteClass.extends.name}.hpp"
</#if>

namespace kurento {

<#list remoteClassDependencies(remoteClass) as dependency>
class ${dependency.name};
</#list>

class ${remoteClass.name}<#if remoteClass.extends??> : public ${remoteClass.extends.name}</#if>
{

public:

  <#if (remoteClass.constructors)??><#rt>
  <#lt><#list remoteClass.constructors as constructor><#rt>
  ${remoteClass.name} (<#rt>
     <#lt><#list constructor.params as param><#rt>
        <#lt>${getCppObjectType(param.type.name)} ${param.name}<#rt>
        <#lt><#if param_has_next>, </#if><#rt>
     <#lt></#list>);
  </#list><#rt>
  <#lt></#if>
  virtual ~${remoteClass.name} ();
  <#list remoteClass.methods as method><#rt>
  <#if method_index = 0 >

  </#if>
  ${getCppObjectType(method.return,false)} ${method.name} (<#rt>
      <#lt><#list method.params as param>${getCppObjectType(param.type.name)} ${param.name}<#if param_has_next>, </#if></#list>);
  </#list>

  <#if (remoteClass.constructors)??>
  class Factory
  {
  public:
    static Factory getFactory() {
      return Factory::factory;
    };

    virtual std::shared_ptr<MediaObject> createObject (const Json::Value
        &params) throw (JsonRpc::CallException);

    virtual std::string getName () {
      return "${remoteClass.name}";
    };

  private:
    <#list remoteClass.constructors as constructor><#rt>
    virtual std::shared_ptr<MediaObject> createObject (<#rt>
     <#lt><#list constructor.params as param><#rt>
        <#lt>${getCppObjectType(param.type.name)} ${param.name}<#rt>
        <#lt><#if param_has_next>, </#if><#rt>
     <#lt></#list>);
   </#list>

    static Factory factory;
  };

  </#if>
};

} /* kurento */

#endif /*  __${camelToUnderscore(remoteClass.name)}_HPP__ */
