#!/usr/bin/env node

var spawn   = require('child_process').spawn
var resolve = require('path').resolve

var eachSeries = require('async').eachSeries


function generate(moduleName, callback)
{
  var options =
  {
    cwd: resolve('node_modules', moduleName),
    stdio: 'inherit'
  };

  spawn(process.execPath, [resolve('scripts/_generate.js')], options)
  .on('exit', callback)
}


var plugins =
[
  'kurento-client-core',
  'kurento-client-elements',
  'kurento-client-filters'
]

eachSeries(plugins, generate, process.exit.bind(process))
