#!/usr/bin/env node

var spawn   = require('child_process').spawn
var resolve = require('path').resolve


function generate(moduleName)
{
  var options =
  {
    cwd: resolve('node_modules', moduleName),
    stdio: 'inherit'
  };

  spawn(process.execPath, [resolve('scripts/_generate.js')], options)
}


generate('kurento-client-core')
generate('kurento-client-elements')
generate('kurento-client-filters')
