#!/usr/bin/env node

var fs    = require('fs')
var spawn = require('child_process').spawn

const LINK_PATH = 'node_modules/kurento-client'

fs.unlink(LINK_PATH, function(error)
{
  if(error && error.code != 'ENOENT') console.warn(error);

  fs.symlinkSync('..', LINK_PATH)

  var args =
  [
    '-c', 'kurentoClient:.',
    '-c', 'node_modules/qunit-reporter-junit',
    '-c', 'wock:node_modules/wock',
    '-c', 'test/_common.js',
    '-c', 'test/_proxy.js',
    'test/'
  ]

  spawn('qunit-cli', args, {stdio: 'inherit'})
  .on('close', function(code)
  {
    fs.unlink(LINK_PATH);
  });
})
