name: "server deploy aws (child)"

on:
  # Triggered from other workflows.
  workflow_call:
    inputs:
      jobRelease:
        description: "jobRelease: Enable to build release versions; disable for development builds"
        required: false
        type: "boolean"
        default: false

defaults:
  run:
    shell: "bash --noprofile --norc -o errexit -o errtrace -o pipefail -o nounset -o xtrace {0}"

jobs:
  build:
    # AWS templates are not updated for development builds.
    if: ${{ inputs.jobRelease }}
    runs-on: ["self-hosted"]
    timeout-minutes: 30
    steps:
      # Action: https://github.com/actions/checkout
      - name: "Checkout"
        uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1

      - name: "Configure the environment for ci-scripts/"
        working-directory: "ci-scripts/"
        run: |
          echo "$PWD" >>$GITHUB_PATH
          echo "KURENTO_SCRIPTS_HOME=$PWD" >>$GITHUB_ENV
          echo "JOB_TIMESTAMP=$(date --utc +%Y%m%d%H%M%S)" >>$GITHUB_ENV

      # Action: https://github.com/actions/download-artifact
      - name: "Copy artifacts from previous jobs"
        id: "copy-artifacts"
        uses: "actions/download-artifact@v4"
        with:
          path: "artifacts/"

      - name: "Run job script"
        env:
          JOB_RELEASE: "${{ inputs.jobRelease }}"
        working-directory: "artifacts/"
        run: "ci_job_deploy_aws_cf.sh"
